---

- hosts: all
  become: true
  vars:
    apache_package: "{{ 'apache2' if ansible_os_family == 'Debian' else 'httpd' }}"
    php_package: "{{ 'php' if ansible_os_family == 'Debian' else 'php' }}"
  tasks:

    # ------------------------------------
    # Ubuntu/Debian: use package module
    # ------------------------------------
    - name: Install Apache and PHP on Ubuntu
      ansible.builtin.package:
        name:
          - "{{ apache_package }}"
          - "{{ php_package }}"
        state: latest
        update_cache: yes
      when: ansible_os_family == "Debian"

    # ------------------------------------
    # Fedora: fallback using shell to avoid dnf5 bug
    # ------------------------------------
    - name: Install Apache and PHP on Fedora
      ansible.builtin.shell: "dnf install -y {{ apache_package }} {{ php_package }}"
      when: ansible_os_family == "RedHat"