---

- hosts: all
  become: true
  pre_tasks:

    # --------------------------------
    # Server Updates on Redhat servers
    # --------------------------------
    - name: Install updates (RedHat)
      tags: always
      ansible.builtin.command: dnf upgrade -y
      changed_when: false
      when: ansible_os_family == "RedHat"

    # --------------------------------
    # Server Updates on Redhat servers
    # --------------------------------
    - name: Install updates (Debian)
      tags: always
      apt:
        update_cache: yes
      changed_when: false
      when: ansible_os_family == "Debian"

# --------------------------------
# Tasks by Role
# --------------------------------

- hosts: all
  become: true
  roles: 
    - base

- hosts: workstations
  become: true
  roles: 
    - workstations

- hosts: web_servers
  become: true
  roles:
    - web_servers

- hosts: db_servers
  become: true
  roles:
    - db_servers

- hosts: file_servers
  become: true
  roles:
    - file_servers