---
# ------------
# All machines
# ------------

- hosts: all
  become: true
  vars:
    apache_package: "{{ 'apache2' if ansible_os_family == 'Debian' else 'httpd' }}"
    php_package: "{{ 'php' if ansible_os_family == 'Debian' else 'php' }}"
  pre_tasks:

    # --------------------------------
    # Server Updates on Redhat servers
    # --------------------------------
    - name: Install updates (RedHat)
      tags: always
      ansible.builtin.command: dnf upgrade -y
      changed_when: false
      when: ansible_os_family == "RedHat"

    - name: Install updates (Debian)
      tags: always
      apt:
        update_cache: yes
      changed_when: false
      when: ansible_os_family == "Debian"

- hosts: all
  become: true
  tasks:

  - name: add ssh key for simone
    tags: always
    authorized_key:
      user: simone
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGbtgoisTeku8o0ulET8qEbNsAc+SahBEd5+OGbRQpnP ansible key"

# ------------
# Workstations
# ------------

- hosts: workstations
  become: true
  tasks:

  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.14.6/terraform_1.14.6_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0775
      owner: root
      group: root

# ------------
# Web Servers
# ------------

- hosts: web_servers
  become: true
  vars:
    apache_package: "{{ 'apache2' if ansible_os_family == 'Debian' else 'httpd' }}"
    php_package: "{{ 'php' if ansible_os_family == 'Debian' else 'php' }}"
  tasks:

    # ------------------------------------
    # Ubuntu/Debian: Install apache and php for Ubuntu
    # ------------------------------------
    - name: Install Apache and PHP on Ubuntu
      tags: apache,apache2,ubuntu
      ansible.builtin.package:
        name:
          - "{{ apache_package }}"
          - "{{ php_package }}"
        state: latest
      when: ansible_os_family == "Debian"

    # ------------------------------------
    # Fedora: Install apache and php for Fedora servers
    # Fedora: fallback method: using shell to avoid dnf5 bug
    # ------------------------------------
    - name: Install Apache and PHP on Fedora
      tags: apache,centos,httpd
      ansible.builtin.shell: "dnf install -y {{ apache_package }} {{ php_package }}"
      when: ansible_os_family == "RedHat"

    - name: Start httpd (Fedora)
      tags: apache,fedora, httpd
      service: 
        name: httpd
        state: started
        enabled: yes
      when: ansible_os_family == "RedHat"

    - name: copy default html file for ansible_ssh_private_key_file
      tags: apache, apache2, httpd
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644

# ------------
# Db Servers
# ------------

- hosts: db_servers
  become: true
  tasks:
  
    - name: Install maria db (Fedora)
      tags: fedora,db,mariadb
      dnf5: 
        name: mariadb
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Install maria db (Ubuntu)
      tags: ubuntu,mariabd,bd
      apt:
        name: mariadb-server
        state: latest
      when: ansible_os_family == "Debian" 

# ------------
# File Servers
# ------------

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest