---

- hosts: all
  become: true
  vars:
    apache_package: "{{ 'apache2' if ansible_os_family == 'Debian' else 'httpd' }}"
    php_package: "{{ 'php' if ansible_os_family == 'Debian' else 'php' }}"
  pre_tasks:

    # --------------------------------
    # Server Updates on Redhat servers
    # --------------------------------
    - name: Install updates (RedHat)
      tags: always
      ansible.builtin.command: dnf upgrade -y
      when: ansible_os_family == "RedHat"

    - name: Install updates (Debian)
      tags: always
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_os_family == "Debian"

- hosts: web_servers
  become: true
  vars:
    apache_package: "{{ 'apache2' if ansible_os_family == 'Debian' else 'httpd' }}"
    php_package: "{{ 'php' if ansible_os_family == 'Debian' else 'php' }}"
  tasks:

    # ------------------------------------
    # Ubuntu/Debian: Install apache and php for Ubuntu
    # ------------------------------------
    - name: Install Apache and PHP on Ubuntu
      tags: apache,apache2,ubuntu
      ansible.builtin.package:
        name:
          - "{{ apache_package }}"
          - "{{ php_package }}"
        state: latest
      when: ansible_os_family == "Debian"

    # ------------------------------------
    # Fedora: Install apache and php for Fedora servers
    # Fedora: fallback method: using shell to avoid dnf5 bug
    # ------------------------------------
    - name: Install Apache and PHP on Fedora
      tags: apache,centos,httpd
      ansible.builtin.shell: "dnf install -y {{ apache_package }} {{ php_package }}"
      when: ansible_os_family == "RedHat"

- hosts: db_servers
  become: true
  tasks:
  
    - name: Install maria db (Fedora)
      tags: fedora,db,mariadb
      dnf5: 
        name: mariadb
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Install maria db (Ubuntu)
      tags: ubuntu,mariabd,bd
      apt:
        name: mariadb-server
        state: latest
      when: ansible_os_family == "Debian" 

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest